# Generated by Django 3.0.8 on 2020-07-09 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64)),
                ('project_description', models.CharField(max_length=1024)),
                ('current_status', models.TextField(max_length=64)),
                ('github', models.URLField()),
                ('started_year', models.PositiveSmallIntegerField()),
                ('last_modified', models.PositiveSmallIntegerField()),
                ('scope', models.TextField(max_length=1024)),
                ('team', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
