# Generated by Django 3.0.8 on 2020-07-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_project_deployed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='background',
            field=models.ImageField(null=True, upload_to='projects/backgrounds/'),
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.ImageField(null=True, upload_to='projects/icons/'),
        ),
    ]
