# Generated by Django 3.0.8 on 2020-07-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0001_initial'),
        ('Projects', '0005_auto_20200711_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='techstack',
            field=models.ManyToManyField(null=True, related_name='projects', to='Nibblites.TechStack'),
        ),
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='projects/icons/'),
        ),
    ]
