# Generated by Django 3.0.8 on 2020-07-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0002_auto_20200712_0139'),
        ('Projects', '0006_auto_20200712_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='techstack',
            field=models.ManyToManyField(related_name='projects', to='Nibblites.TechStack'),
        ),
    ]
