# Generated by Django 3.0.8 on 2020-07-20 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0004_auto_20200720_1819'),
        ('Projects', '0008_auto_20200713_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='techstack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='Nibblites.TechStack'),
        ),
    ]
