# Generated by Django 3.0.8 on 2020-07-22 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0004_auto_20200720_1819'),
        ('Projects', '0009_auto_20200720_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='projects/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='last_modified',
            field=models.PositiveSmallIntegerField(default=2017),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='techstack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='Nibblites.TechStack'),
        ),
    ]
