# Generated by Django 3.0.8 on 2020-07-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20200708_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profiles',
            field=models.ManyToManyField(through='Accounts.Profile', to='Accounts.Website'),
        ),
    ]
