# Generated by Django 3.0.8 on 2020-07-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0001_initial'),
        ('Accounts', '0007_auto_20200709_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='techstack',
            field=models.ManyToManyField(null=True, related_name='users', to='Nibblites.TechStack'),
        ),
    ]
