# Generated by Django 3.0.8 on 2020-07-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0002_auto_20200712_0139'),
        ('Accounts', '0008_user_techstack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='techstack',
            field=models.ManyToManyField(related_name='users', to='Nibblites.TechStack'),
        ),
    ]
