# Generated by Django 3.0.8 on 2020-07-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_auto_20200713_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_links',
        ),
        migrations.DeleteModel(
            name='User_links',
        ),
    ]
