# Generated by Django 3.0.8 on 2020-07-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_auto_20200716_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_token',
            field=models.CharField(editable=False, max_length=512, null=True, unique=True),
        ),
    ]
