# Generated by Django 3.0.8 on 2020-07-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_user_firebase_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firebase_token',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
