# Generated by Django 3.0.8 on 2020-07-03 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_starting_year', models.PositiveSmallIntegerField()),
                ('session_ending_year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('codechef', models.URLField()),
                ('codeforces', models.URLField()),
                ('hackerrank', models.URLField()),
                ('slack', models.URLField()),
                ('behance', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('full_name', models.CharField(max_length=32)),
                ('phone_no', models.CharField(max_length=16)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nibblites.Designation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nibblites.Session')),
                ('user_links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nibblites.User_links')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nibblites.Year')),
            ],
        ),
    ]
