# Generated by Django 3.0.8 on 2020-07-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='app_tech_stack',
            field=models.ManyToManyField(blank=True, to='Nibblites.AppTech'),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='backend_stack',
            field=models.ManyToManyField(blank=True, to='Nibblites.Backend'),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='frontend_stack',
            field=models.ManyToManyField(blank=True, to='Nibblites.Frontend'),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='languages',
            field=models.ManyToManyField(blank=True, to='Nibblites.Language'),
        ),
    ]
