# Generated by Django 3.0.8 on 2020-07-03 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0002_auto_20200704_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_links',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Nibblites.User_links'),
        ),
    ]
