# Generated by Django 3.0.8 on 2020-07-11 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0002_auto_20200712_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techstack',
            old_name='app_tech_stack',
            new_name='app_techs',
        ),
        migrations.RenameField(
            model_name='techstack',
            old_name='backend_stack',
            new_name='backend_techs',
        ),
        migrations.RenameField(
            model_name='techstack',
            old_name='frontend_stack',
            new_name='frontend_techs',
        ),
    ]
