# Generated by Django 3.0.8 on 2020-07-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0003_auto_20200704_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_links',
            name='codeingame',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user_links',
            name='codewars',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user_links',
            name='hackerearth',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user_links',
            name='leetcode',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user_links',
            name='others',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user_links',
            name='spoj',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user_links',
            name='topcoder',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='user_links',
            name='codechef',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='user_links',
            name='codeforces',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='user_links',
            name='hackerrank',
            field=models.URLField(null=True),
        ),
    ]
