# Generated by Django 3.0.8 on 2020-07-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0004_auto_20200704_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_links',
            name='others',
        ),
    ]
