# Generated by Django 3.0.8 on 2020-07-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0005_remove_user_links_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_links',
            name='behance',
            field=models.URLField(null=True),
        ),
    ]
