# Generated by Django 3.0.8 on 2020-07-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0006_user_links_behance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adminssion_no',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='university_roll_no',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
