# Generated by Django 3.0.8 on 2020-07-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0008_auto_20200704_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=8)),
                ('branch_full_form', models.CharField(max_length=32)),
            ],
        ),
    ]
