# Generated by Django 3.0.8 on 2020-07-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0009_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_full_form',
            field=models.CharField(max_length=64),
        ),
    ]
