# Generated by Django 3.0.8 on 2020-07-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0012_auto_20200704_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Nibblites.Club'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='club',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='designation',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
