# Generated by Django 3.0.8 on 2020-07-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0014_auto_20200704_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_links',
            name='behance',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_links',
            name='codechef',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_links',
            name='codeforces',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_links',
            name='codeingame',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_links',
            name='codewars',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_links',
            name='hackerearth',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_links',
            name='hackerrank',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_links',
            name='leetcode',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_links',
            name='spoj',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_links',
            name='topcoder',
            field=models.URLField(blank=True, null=True),
        ),
    ]
