# Generated by Django 3.0.8 on 2020-07-05 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0016_auto_20200704_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_links',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_links',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='Nibblites.User_links'),
        ),
    ]
