# Generated by Django 3.0.8 on 2020-07-05 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0017_auto_20200706_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='rank',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_links',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Nibblites.User_links'),
        ),
    ]
