# Generated by Django 3.0.8 on 2020-07-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0019_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_links',
            name='fossbyte',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_links',
            name='medium',
            field=models.URLField(blank=True, null=True),
        ),
    ]
