# Generated by Django 3.0.8 on 2020-07-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0020_auto_20200706_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_links',
            name='kaggle',
            field=models.URLField(blank=True, null=True),
        ),
    ]
