# Generated by Django 3.0.8 on 2020-07-06 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0021_user_links_kaggle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('used_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nibblites.User')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nibblites.Website', to_field='website_name')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profile_links',
            field=models.ManyToManyField(through='Nibblites.Profiles', to='Nibblites.Website'),
        ),
    ]
