# Generated by Django 3.0.8 on 2020-07-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0022_auto_20200706_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='used_id',
            new_name='user',
        ),
    ]
