# Generated by Django 3.0.8 on 2020-07-06 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0023_auto_20200706_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_links',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='Nibblites.User'),
        ),
    ]
