# Generated by Django 3.0.8 on 2020-07-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nibblites', '0025_auto_20200707_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_links',
        ),
        migrations.DeleteModel(
            name='User_links',
        ),
    ]
