# Generated by Django 3.0.8 on 2020-07-13 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_entered', models.DateTimeField()),
                ('attendee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=64)),
                ('additional_info', models.TextField(blank=True, max_length=512, null=True)),
                ('venue', models.CharField(max_length=64)),
                ('announcer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs_announced', to=settings.AUTH_USER_MODEL)),
                ('attendees', models.ManyToManyField(related_name='labs_attended', through='Attendance.Attendance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Attendance.Lab'),
        ),
    ]
