# Generated by Django 3.0.8 on 2020-07-15 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_auto_20200714_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
    ]
