# Generated by Django 3.0.8 on 2020-07-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0003_lab_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='date_time',
        ),
        migrations.AddField(
            model_name='lab',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
