# Generated by Django 3.0.8 on 2020-07-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0004_auto_20200715_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
    ]
