# Generated by Django 3.0.8 on 2020-07-18 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Attendance', '0007_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='announcer',
        ),
        migrations.AddField(
            model_name='lab',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs_organized', to=settings.AUTH_USER_MODEL),
        ),
    ]
