# Generated by Django 3.0.8 on 2020-07-19 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Attendance', '0008_auto_20200718_0416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='notify',
            new_name='notify_groups',
        ),
        migrations.AddField(
            model_name='announcement',
            name='notify_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
