# Generated by Django 3.0.8 on 2020-07-20 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('Attendance', '0009_auto_20200719_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='notify_groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='notify_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
