# Generated by Django 3.0.8 on 2020-07-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0010_auto_20200720_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(max_length=365),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
